import type { BuffSkill, ElementalSkill, LineageSkill } from '../types/skill'

export const LINEAGE_SKILLS: Record<string, LineageSkill[]> = {
  uchiha: [
    {
      id: 'sharingan-dousatsugan',
      name: 'Sharingan Dousatsugan',
      description: 'Aguça a percepção e prevê os movimentos do adversário.',
      baseDamage: 50,
      scalingAttribute: 'genjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'sharingan-copiador',
      name: 'Sharingan Copiador',
      description: 'Analisa e replica as técnicas do inimigo em combate.',
      baseDamage: 100,
      scalingAttribute: 'genjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'magen-kasegui',
      name: 'Magen: Kasegui',
      description: 'Ilusão de aprisionamento por estacas que restringe as ações do alvo.',
      baseDamage: 150,
      scalingAttribute: 'genjutsu',
      scalingPercent: 0.4,
    },
  ],
  uzumaki: [
    {
      id: 'fuuinjutsu-fuuka-houin',
      name: 'Fuuinjutsu: Fuuka Houin',
      description: 'Avança utilizando o selo na palma da mão para selar o kawarimi do alvo durante 12 segundos.',
      imageSrc: '/images/lineages/uzumaki-1.png',
      baseDamage: 50,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Selamento de Kawarimi',
          description: 'Impede o alvo de utilizar a técnica de substituição (kawarimi).',
          duration: '12s',
        },
      ],
    },
    {
      id: 'fuuinjutsu-kongou-fuusa',
      name: 'Fuuinjutsu: Kongou Fuusa',
      description: 'Utiliza o selamento de correntes de chakra douradas para causar dano ao oponente.',
      imageSrc: '/images/lineages/uzumaki-2.png',
      baseDamage: 100,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'fuuinjutsu-shiki-fuujin',
      name: 'Fuuinjutsu: Shiki Fuujin',
      description: 'Invoca o ceifeiro da morte para selar o chakra do oponente por 24 segundos.',
      imageSrc: '/images/lineages/uzumaki-3.png',
      baseDamage: 150,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Selamento de Chakra',
          description: 'Bloqueia completamente o chakra do oponente, impedindo a conjuração de qualquer jutsu.',
          duration: '24s',
        },
      ],
    },
  ],
  senju: [
    {
      id: 'benishigure',
      name: 'Benishigure',
      description: 'O usuário salta graciosamente para a frente e desfere um golpe esmagador no chão com força colossal, quebrando a defesa do alvo.',
      imageSrc: '/images/lineages/senju-1.png',
      baseDamage: 50,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Quebra de Defesa',
          description: 'Rompe a postura defensiva do inimigo, deixando-o vulnerável a novos ataques.',
          duration: '3s',
        },
      ],
    },
    {
      id: 'ouka-resshou',
      name: 'Ouka Resshou',
      description: 'Realiza um soco carregado de chakra concentrado que, ao atingir o alvo, libera uma poderosa onda de choque que o levanta no ar.',
      imageSrc: '/images/lineages/senju-2.png',
      baseDamage: 100,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Levantamento (Knockup)',
          description: 'Arremessa o oponente para cima, interrompendo qualquer ação em andamento.'
        },
      ],
    },
    {
      id: 'tsuutenkyaku',
      name: 'Tsuutenkyaku',
      description: 'Concentra uma quantidade massiva de chakra no calcanhar e desfere um poderoso chute de machado descendente, causando dano extremo e levantando o alvo com o impacto.',
      imageSrc: '/images/lineages/senju-3.png',
      baseDamage: 150,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Levantamento (Knockup)',
          description: 'Arremessa o oponente para cima, interrompendo qualquer ação em andamento.'
        },
      ],
    },
  ],
  hyuuga_souke: [
    {
      id: 'byakugan-juuken-souke',
      name: 'Byakugan: Juuken',
      description: 'Desperta o Byakugan, garantindo percepção total do campo de batalha. Amplifica o Taijutsu em 10% e permite drenar o chakra inimigo através do Juuken, consumindo o chakra do usuário passivamente por segundo. Pode ativar a visão para enxergar tudo ao redor.',
      imageSrc: '/images/elementals/unknown.png',
      baseDamage: 0,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0,
      effects: [
        {
          type: 'buff',
          name: 'Visão Panorâmica (Byakugan)',
          description: 'Aumenta o Taijutsu em 10%, drena o chakra do oponente a cada golpe e consome o chakra do usuário passivamente por segundo.',
          percentStats: { taijutsu: 10 },
        },
      ],
    },
    {
      id: 'hakke-kuuhekishou',
      name: 'Hakke Kuuhekishou',
      description: 'Parede de vácuo disparada pelas palmas das mãos.',
      baseDamage: 100,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'juuho-soushiken',
      name: 'Juuho Soushiken',
      description: 'Passo gentil dos punhos de leões gêmeos.',
      baseDamage: 150,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
    },
  ],
  hyuuga_bunke: [
    {
      id: 'byakugan-juuken-bouke',
      name: 'Byakugan: Juuken',
      description: 'Desperta o Byakugan, garantindo percepção total do campo de batalha. Amplifica o Taijutsu em 10% e permite drenar o chakra inimigo através do Juuken, consumindo o chakra do usuário passivamente por segundo. Pode ativar a visão para enxergar tudo ao redor.',
      imageSrc: '/images/elementals/unknown.png',
      baseDamage: 0,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0,
      effects: [
        {
          type: 'buff',
          name: 'Visão Panorâmica (Byakugan)',
          description: 'Aumenta o Taijutsu em 10%, drena o chakra do oponente a cada golpe e consome o chakra do usuário passivamente por segundo.',
          percentStats: { taijutsu: 10 },
        },
      ],
    },
    {
      id: 'hakkeshou-kaiten',
      name: 'Hakkeshou Kaiten',
      description: 'Libera uma quantidade massiva de chakra por todos os tenketsu do corpo enquanto gira rapidamente, criando uma barreira giratória impenetrável que causa dano a todos os inimigos ao redor.',
      imageSrc: '/images/elementals/unknown.png',
      baseDamage: 100,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'buff',
          name: 'Barreira Giratória',
          description: 'Repele projéteis, ataques físicos e causa dano em área aos oponentes próximos.',
        },
      ],
    },
    {
      id: 'hakke-sanjuu-ni-shou',
      name: 'Hakke Sanjuu Ni Shou',
      description: 'Executa uma sequência veloz e implacável de 32 golpes nos pontos de chakra (tenketsu) dos oponentes em área, causando dano massivo.',
      imageSrc: '/images/elementals/unknown.png',
      baseDamage: 150,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Drenagem de Chakra',
          description: 'Drena continuamente o chakra do oponente a cada golpe desferido nos pontos de chakra.',
          duration: '5s',
        },
      ],
    },
  ],
  nara: [
    {
      id: 'kagemane',
      name: 'Kagemane',
      description: 'Estende a sombra do usuário para conectar-se à do oponente, paralisando seus movimentos e permitindo enforcá-lo com sombras adicionais para causar dano',
      imageSrc: '/images/lineages/nara-1.png',
      baseDamage: 50,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Paralisia e Enforcamento',
          description: 'O inimigo fica completamente paralisado e sofre dano ao ser enforcado por sombras adicionais.',
          duration: '2s',
        },
      ],
    },
    {
      id: 'kage-nui',
      name: 'Kage Nui',
      description: 'Materializa sombras pontiagudas em formato de agulhas físicas que surgem do solo para perfurar o oponente. Não restringe a movimentação do alvo, concentrando todo o seu poder em causar dano puro.',
      imageSrc: '/images/lineages/nara-2.png',
      baseDamage: 100,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'kageyose',
      name: 'Kageyose',
      description: 'Cria uma densa e ampla área de sombras que converge sob os inimigos, prendendo-os no local com a possibilidade de detonar as sombras acumuladas para um impacto devastador.',
      imageSrc: '/images/lineages/nara-3.png',
      baseDamage: 150,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Sombras Aprisionadoras',
          description: 'Prende os inimigos em uma área de sombras com possibilidade de detonação explosiva subsequente.',
          duration: '4s',
        },
      ],
    },
  ],
  sabaku: [
    {
      id: 'suna-no-kouken',
      name: 'Suna no Kouken',
      description: 'Envia braços de areia que perseguem e causam atordoamento (stun) no inimigo.',
      imageSrc: '/images/lineages/sabaku-1.png',
      baseDamage: 50,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'debuff',
          name: 'Atordoamento (Stun)',
          description: 'O inimigo fica imobilizado e incapacitado de agir.',
          duration: '1s',
        },
      ],
    },
    {
      id: 'suna-no-tate',
      name: 'Suna no Tate',
      description: 'Cria uma defesa absoluta de areia ao seu redor. Concede imunidade a dano e controle de grupo enquanto durar o chakra. Consome chakra passivamente por segundo e sofre redução de chakra ao receber golpes.',
      imageSrc: '/images/lineages/sabaku-2.png',
      baseDamage: 100,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
      effects: [
        {
          type: 'buff',
          name: 'Defesa Absoluta',
          description: 'Imunidade total a danos e efeitos de controle de grupo. Consome chakra continuamente e ao receber ataques.',
        },
      ],
    },
    {
      id: 'sabaku-soutaisou',
      name: 'Sabaku Soutaisou',
      description: 'Executa o Grande Mausoléu de Areia (Grand Sand Mausoleum) em uma ampla área, prendendo e esmagando todos os oponentes.',
      imageSrc: '/images/lineages/sabaku-3.png',
      baseDamage: 150,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4
    },
  ],
  lotus: [
    {
      id: 'dainamikku-entori',
      name: 'Dainamikku Entori',
      description: 'Entrada dinâmica com chute surpresa de grande impacto.',
      baseDamage: 50,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'konoha-shoufuu',
      name: 'Konoha Shoufuu',
      description: 'Vendaval da folha que arremessa o oponente para o alto.',
      baseDamage: 100,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'hachimon-tonkou',
      name: 'Hachimon Tonkou',
      description: 'Liberação de limitadores de energia para amplificação física.',
      baseDamage: 150,
      scalingAttribute: 'taijutsu',
      scalingPercent: 0.4,
    },
  ],
  yuuhi: [
    {
      id: 'magen-jubaku-satsu',
      name: 'Magen: Jubaku Satsu',
      description: 'Ilusão demoníaca que prende o alvo em uma árvore ilusória.',
      baseDamage: 50,
      scalingAttribute: 'genjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'magen-hanagasumi',
      name: 'Magen: Hanagasumi',
      description: 'Ilusão de pétalas de flores dispersas para desorientação.',
      baseDamage: 100,
      scalingAttribute: 'genjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'magen-sanshin',
      name: 'Magen: Sanshin',
      description: 'Ilusão tripla que confunde os sentidos e percepções do oponente.',
      baseDamage: 150,
      scalingAttribute: 'genjutsu',
      scalingPercent: 0.4,
    },
  ],
  momochi: [
    {
      id: 'kirigakure-no-jutsu',
      name: 'Kirigakure no Jutsu',
      description: 'Ocultação na névoa densa para preparar investidas furtivas.',
      baseDamage: 50,
      scalingAttribute: 'kenjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'sairento-kiringu',
      name: 'Sairento Kiringu',
      description: 'Ataque surpresa letal executado em silêncio absoluto.',
      baseDamage: 100,
      scalingAttribute: 'kenjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'kijingiri-sakki',
      name: 'Kijingiri: Sakki',
      description: 'Corte devastador com a lâmina decapitadora imbuída de intenção assassina.',
      baseDamage: 150,
      scalingAttribute: 'kenjutsu',
      scalingPercent: 0.4,
    },
  ],
}

export const ELEMENTAL_SKILLS: Record<string, ElementalSkill[]> = {
  fire: [
    {
      id: 'katon-endan-goukakyuu',
      name: 'Katon: Endan - Goukakyuu',
      description: 'Disparo de fogo que gera uma enorme bola de chamas.',
      imageSrc: '/images/elementals/katon-1.png',
      baseDamage: 40,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.2,
    },
    {
      id: 'katon-housenka',
      name: 'Katon: Housenka',
      description: 'Múltiplas bolas de fogo menores disparadas em direções variadas.',
      imageSrc: '/images/elementals/katon-2.png',
      baseDamage: 80,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'katon-haijingakure',
      name: 'Katon: Haijingakure',
      description: 'Névoa de cinzas superaquecidas que causa dano e reduz a visibilidade.',
      imageSrc: '/images/elementals/katon-3.png',
      baseDamage: 120,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.6,
    },
    {
      id: 'katon-karyuuendan',
      name: 'Katon: Karyuuendan',
      description: 'Sopro de chamas espesso e extremamente destrutivo imitando o fogo do dragão.',
      imageSrc: '/images/elementals/katon-4.png',
      baseDamage: 200,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.8,
    },
    // {
    //   id: 'katon-gouka-mekkyaku',
    //   name: 'Katon: Gouka Mekkyaku',
    //   description: 'Grande aniquilação de fogo de proporções colossais.',
    //   baseDamage: 320,
    //   scalingAttribute: 'ninjutsu',
    //   scalingPercent: 1.0,
    // },
  ],
  wind: [
    {
      id: 'fuuton-tatsumaki-kou',
      name: 'Fuuton: Tatsumaki Kou',
      description: 'Lança um tornado afiado de vento em direção ao oponente.',
      imageSrc: '/images/elementals/fuuton-1.png',
      baseDamage: 40,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.2,
    },
    {
      id: 'fuuton-shinkuuha',
      name: 'Fuuton: Shinkuuha',
      description: 'Lâminas de vácuo cortantes disparadas com movimento de sopro.',
      imageSrc: '/images/elementals/fuuton-2.png',
      baseDamage: 80,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'fuuton-kuchiyose-kirikiri-mai',
      name: 'Fuuton: Kuchiyose Kirikiri Mai',
      description: 'Invocação de vendavais cortantes em grande área.',
      imageSrc: '/images/elementals/fuuton-3.png',
      baseDamage: 120,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.6,
    },
    {
      id: 'fuuton-kamaitachi',
      name: 'Fuuton: Kamaitachi',
      description: 'Redemoinho de vento cortante que impede defesas diretas.',
      imageSrc: '/images/elementals/fuuton-4.png',
      baseDamage: 200,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.8,
    },
    // {
    //   id: 'fuuton-tatsu-no-oushigoto',
    //   name: 'Fuuton: Tatsu no Oushigoto',
    //   description: 'Tornado de grande pressão do dragão de vento.',
    //   baseDamage: 320,
    //   scalingAttribute: 'ninjutsu',
    //   scalingPercent: 1.0,
    // },
  ],
  lightning: [
    {
      id: 'raiton-chidori-raikiri',
      name: 'Raiton: Chidori / Raikiri',
      description: 'Chakra elétrico concentrado na palma da mão para perfuração de alta velocidade.',
      imageSrc: '/images/elementals/raiton-1.png',
      baseDamage: 40,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.2,
    },
    {
      id: 'raiton-raikyuu',
      name: 'Raiton: Raikyuu',
      description: 'Dispara esferas elétricas teleguiadas em direção ao alvo.',
      imageSrc: '/images/elementals/raiton-2.png',
      baseDamage: 80,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'raiton-nagashi',
      name: 'Raiton: Nagashi',
      description: 'Liberação de eletricidade ao redor do corpo para repelir agressores.',
      imageSrc: '/images/elementals/raiton-3.png',
      baseDamage: 120,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.6,
    },
    {
      id: 'raiton-hebi-ikazuchi',
      name: 'Raiton: Hebi Ikazuchi',
      description: 'Descargas elétricas em forma de serpente com alta capacidade de choque.',
      imageSrc: '/images/elementals/raiton-4.png',
      baseDamage: 200,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.8,
    },
    // {
    //   id: 'raiton-kirin',
    //   name: 'Raiton: Kirin',
    //   description: 'Técnica lendária que invoca um trovão em formato de criatura mitológica.',
    //   baseDamage: 320,
    //   scalingAttribute: 'ninjutsu',
    //   scalingPercent: 1.0,
    // },
  ],
  water: [
    {
      id: 'suiton-teppodama',
      name: 'Suiton: Teppodama',
      description: 'Dispara uma veloz bola de água compressora.',
      imageSrc: '/images/elementals/suiton-1.png',
      baseDamage: 40,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.2,
    },
    {
      id: 'suiton-suikodan',
      name: 'Suiton: Suikodan',
      description: 'Projétil em formato de tubarão feito de água em alta pressão.',
      imageSrc: '/images/elementals/suiton-2.png',
      baseDamage: 80,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'suiton-suirou',
      name: 'Suiton: Suirou',
      description: 'Prisão de água que imobiliza o alvo por tempo determinado.',
      imageSrc: '/images/elementals/suiton-3.png',
      baseDamage: 120,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.6,
    },
    {
      id: 'suiton-suireiha',
      name: 'Suiton: Suireiha',
      description: 'Onda destrutiva contínua de água que arrasta o oponente.',
      imageSrc: '/images/elementals/suiton-4.png',
      baseDamage: 200,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.8,
    },
    // {
    //   id: 'suiton-daikodan',
    //   name: 'Suiton: Daikodan',
    //   description: 'Técnica do grande tubarão de água que absorve chakra do oponente.',
    //   baseDamage: 320,
    //   scalingAttribute: 'ninjutsu',
    //   scalingPercent: 1.0,
    // },
  ],
  earth: [
    {
      id: 'doton-doryuuheki',
      name: 'Doton: Doryuuheki',
      description: 'Erigir uma muralha sólida de terra para proteção.',
      imageSrc: '/images/elementals/doton-1.png',
      baseDamage: 40,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.2,
    },
    {
      id: 'doton-chidoukaku-kouka',
      name: 'Doton: Chidoukaku / Kouka',
      description: 'Alteração de elevação do solo sob o alvo ou endurecimento da pele.',
      imageSrc: '/images/elementals/doton-2.png',
      baseDamage: 80,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.4,
    },
    {
      id: 'doton-dorojigoku',
      name: 'Doton: Dorojigoku',
      description: 'Pântano movediço de lama que engole e causa dano contínuo.',
      imageSrc: '/images/elementals/doton-3.png',
      baseDamage: 120,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.6,
    },
    {
      id: 'doton-doryuudan',
      name: 'Doton: Doryuudan',
      description: 'Invocação de cabeça de dragão de terra que cospe projéteis de pedra.',
      imageSrc: '/images/elementals/doton-4.png',
      baseDamage: 200,
      scalingAttribute: 'ninjutsu',
      scalingPercent: 0.8,
    },
    // {
    //   id: 'doton-toujinbou',
    //   name: 'Doton: Toujinbou',
    //   description: 'Espinho maciço de pedra perfurante que surge do chão.',
    //   baseDamage: 320,
    //   scalingAttribute: 'ninjutsu',
    //   scalingPercent: 1.0,
    // },
  ],
}

export const BUFF_SKILLS: BuffSkill[] = []

export const LINEAGE_BUFF_SKILLS: Record<string, BuffSkill[]> = {
  uchiha: [
    {
      id: 'sharingan-focus',
      name: 'Foco Sharingan',
      imageSrc: '/images/elementals/unknown.png',
      description: 'Refina percepção e controle de genjutsu.',
      effects: [
        {
          type: 'buff',
          name: 'Leitura de movimento',
          description: 'Aumenta Genjutsu em percentual.',
          percentStats: { genjutsu: 10 },
        },
      ],
    },
  ],
  hyuuga_souke: [],
  hyuuga_bunke: [],

  lotus: [
    {
      id: 'lotus-gates',
      name: 'Portões do Lótus',
      imageSrc: '/images/elementals/unknown.png',
      description: 'Liberação progressiva que aumenta o poder físico.',
      effects: [
        {
          type: 'buff',
          name: 'Portões internos',
          description: 'Escolha o nível ativo para aplicar os bônus.',
          levels: [
            {
              level: 1,
              label: '1º Portão',
              description: '+10 Taijutsu.',
              stats: { taijutsu: 10 },
            },
            {
              level: 2,
              label: '2º Portão',
              description: '+20 Taijutsu.',
              stats: { taijutsu: 20 },
            },
            {
              level: 3,
              label: '3º Portão',
              description: '+35 Taijutsu e -50 Vida.',
              stats: { taijutsu: 35, vida: -50 },
            },
          ],
        },
      ],
    },
  ],
  yuuhi: [
    {
      id: 'illusion-mastery',
      name: 'Domínio Ilusório',
      imageSrc: '/images/elementals/unknown.png',
      description: 'Percepção artística avançada e dispersão ilusória.',
      effects: [
        {
          type: 'buff',
          name: 'Arte da ilusão',
          description: 'Aumenta a efetividade de genjutsus.',
          percentStats: { genjutsu: 12 },
        },
      ],
    },
  ],
  momochi: [
    {
      id: 'silent-assassin',
      name: 'Assassino Silencioso',
      imageSrc: '/images/elementals/unknown.png',
      description: 'Técnica silenciosa que amplia a letalidade de cortes com espada.',
      effects: [
        {
          type: 'buff',
          name: 'Corte Letal',
          description: 'Aumenta a efetividade de kenjutsus.',
          percentStats: { kenjutsu: 12 },
        },
      ],
    },
  ],
}
